### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by TheCodedOne** [MinecraftModDevelopmentMods/MMDLib#1]
- [ ] Means not being worked on/not implemented yet
- [x] Means being worked on by someone/implemented already

# Util
- [ ] Simple JSONless model system (Pre 1.8 Style initially)
- [ ] Flat Bedrock Generation/Bedrock Generation Control
- [ ] Leaf Decay Control
- [ ] Exploding Blocks

# ASM
- [x] Horse Armor
- [ ] Fishing Rod

# MC Stuff
- [x] Shield 
- [ ] Minecarts
- [ ] Trees
- [ ] Structure Worldgen (By Structure block schematic and old style import)
# Astro
- [x] Turbo Models
- [x] Annotation Based Configs
- [x] Annotation Checker

# Bookshelf
- [ ] Base code for a TileEntity and TileEntity block
- [x] Graphical GUI button
- [ ] Wrapper particle for the digging particle (default has no constructor)
- [x] Anvil recipes
- [x] Item with built in inventory
- [x] Armor Slot impl
- [x] Fake/Filter Slot impl
- [ ] Basic/Default ItemBlock impl.
- [x] Commonly used BlockStates.
- [x] EnchantmentData wrapper. (serialization support)
- [x] Milibucket enum (commonly used constants for size/amount)
- [x] WeightedSelector (Easy setup for weighted systems)
- [ ] Baubles - Utils & Default Item impl.
- [x] Unlisted object property for blocks. Allows things like World to be a blockstate.
- [ ] Enchantment Level events. **ASM**
- [x] BannerUtils
- [x] BlockUtils
- [x] ClassUtils
- [x] CraftingUtils
- [x] EnchantmentUtils
- [ ] InventoryUtils
- [x] ItemStackUtils
- [ ] MathsUtils
- [x] ModUtils
- [x] NBTUtils
- [ ] NumericUtils (to merge with maths)
- [x] OreDictUtils
- [ ] ParticleUtils
- [x] PlayerUtils
- [x] RenderUtils
- [x] SkullUtils
- [ ] Attribute Cap tweaks **utils**
- [ ] Structure Template Processing

# Possible
- [ ] Guide Book API
- [ ] Title Screen API
- [ ] Loading Screen API

**Comment by darkhax** [comment]
Jas and I discussed syncing in some of the bookshelf features as well. Adding those to the issue now.
